### ISSUE TITLE
Microflow Timer won't close popup (same as issue #7 )

### ISSUE THREAD

**Issue by stapersmaj** [mendix/MicroflowTimer#11]
Same issue as was raised in issue #7 has reappeared (probably due to removing the code snippet below)

                if (!mx.version || parseInt(mx.version.split(".")[0], 10) < 6) {
                    microflowAction.store = {
                        caller: this.mxform
                    };
                } else {
                    microflowAction.origin = this.mxform;
                }

Seems to have reappeared since the conversion from mx.data.action to mx.ui.action

**Comment by JelteMX** [comment]
Again, does [this version](https://github.com/mendix/MicroflowTimer/raw/fix_mx_7/test/widgets/MicroflowTimer.mpk) fix the problem? If so, I am going to merge the fixes in the `fix_mx_7` branch into master and create a new version

**Comment by stapersmaj** [comment]
Yes, it fixed the problem. Thank you!
