### ISSUE TITLE
Microflow keeps running after return false

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/MicroflowTimer#2]
I do calculations in the timed microflow and conditional display the outcome. THe mf returns false but is started again because of the refresh of the Object.

see also my question on the forum: https://mxforum.mendix.com/questions/8008/Microflow-timer-keeps-running-after-return-false

**Comment by pimvdnoll** [comment]
added a test in the testproject for this issue

**Comment by Andries-Smit** [comment]
@Mendix; please push this update to the appstore

**Comment by RoelandSalij** [comment]
@Andries-Smit; Done
